### PR TITLE
MAWB-8: create a YoutubeResponseDto class

### PR DESCRIPTION
**Pull request by romaanankin**

### CODE REVIEW

**Comment by boroda4436** [comment]
@romaanankin please write issue number when you are creating new PR. Also "check pls" is not informative PR name

**Comment by boroda4436** [comment]
@Dimitriy1 @danny73210 @BondarenkoJek @Dinexpod @Illia1927 any comments?

**Comment by Illia1927** [comment]
Why do we need DTO?

**Comment by boroda4436** [comment]
Circle CI rebuild

**Comment by boroda4436** [comment]
Circle CI rebuild

**Pull request closed without merging**
